-- Test dataset bootstrap script for migration validation
-- Execute only the section matching your DB engine.

/* =========================================================
   [SECTION A] MySQL 8.x
   ========================================================= */

CREATE DATABASE IF NOT EXISTS member_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS item_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS cust_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE member_db;

CREATE TABLE IF NOT EXISTS mbr_base (
  id BIGINT PRIMARY KEY,
  member_no VARCHAR(30),
  mbr_name VARCHAR(100),
  resident_no VARCHAR(64),
  mobile_no VARCHAR(30),
  mbr_detail VARCHAR(255),
  mbr_auth VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS mbr_detail (id BIGINT PRIMARY KEY, email VARCHAR(150), addr_detail VARCHAR(255), note VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mbr_log_01 (id BIGINT PRIMARY KEY, event_type VARCHAR(40), message VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mbr_log_02 (id BIGINT PRIMARY KEY, event_type VARCHAR(40), message VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mbr_log_03 (id BIGINT PRIMARY KEY, event_type VARCHAR(40), message VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mbr_auth (id BIGINT PRIMARY KEY, auth_code VARCHAR(100), auth_desc VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mbr_sns (id BIGINT PRIMARY KEY, sns_type VARCHAR(30), sns_id VARCHAR(120), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mbr_point (id BIGINT PRIMARY KEY, point_amt INT, reason VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mbr_grade (id BIGINT PRIMARY KEY, grade_code VARCHAR(30), grade_name VARCHAR(100), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mbr_dormant (id BIGINT PRIMARY KEY, dormant_yn CHAR(1), dormant_at TIMESTAMP NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

INSERT INTO mbr_base (id, member_no, mbr_name, resident_no, mobile_no, mbr_detail, mbr_auth) VALUES
  (1, 'M0001', 'Kim DA', '900101-1234567', '01012345678', 'damo_payload_001', 'damo_auth_001')
ON DUPLICATE KEY UPDATE mbr_name=VALUES(mbr_name);
INSERT INTO mbr_detail (id, email, addr_detail, note) VALUES
  (1, 'kim.da@example.com', 'Seoul Test-gu 101', 'seed')
ON DUPLICATE KEY UPDATE email=VALUES(email);
INSERT INTO mbr_log_01 (id, event_type, message) VALUES (1, 'LOGIN', 'seed') ON DUPLICATE KEY UPDATE message=VALUES(message);
INSERT INTO mbr_log_02 (id, event_type, message) VALUES (1, 'LOGIN', 'seed') ON DUPLICATE KEY UPDATE message=VALUES(message);
INSERT INTO mbr_log_03 (id, event_type, message) VALUES (1, 'LOGIN', 'seed') ON DUPLICATE KEY UPDATE message=VALUES(message);
INSERT INTO mbr_auth (id, auth_code, auth_desc) VALUES (1, 'ROLE_USER', 'seed') ON DUPLICATE KEY UPDATE auth_desc=VALUES(auth_desc);
INSERT INTO mbr_sns (id, sns_type, sns_id) VALUES (1, 'KAKAO', 'kakao_001') ON DUPLICATE KEY UPDATE sns_id=VALUES(sns_id);
INSERT INTO mbr_point (id, point_amt, reason) VALUES (1, 1000, 'seed') ON DUPLICATE KEY UPDATE point_amt=VALUES(point_amt);
INSERT INTO mbr_grade (id, grade_code, grade_name) VALUES (1, 'GOLD', 'Gold') ON DUPLICATE KEY UPDATE grade_name=VALUES(grade_name);
INSERT INTO mbr_dormant (id, dormant_yn, dormant_at) VALUES (1, 'N', NULL) ON DUPLICATE KEY UPDATE dormant_yn=VALUES(dormant_yn);

USE item_db;
CREATE TABLE IF NOT EXISTS itm_base (id BIGINT PRIMARY KEY, item_no VARCHAR(40), item_name VARCHAR(150), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS itm_price (id BIGINT PRIMARY KEY, price_amt DECIMAL(15,2), currency VARCHAR(10), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS itm_stock (id BIGINT PRIMARY KEY, stock_qty INT, warehouse_cd VARCHAR(30), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS itm_category (id BIGINT PRIMARY KEY, category_cd VARCHAR(40), category_name VARCHAR(100), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS itm_review (id BIGINT PRIMARY KEY, rating INT, review_text VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS itm_qna (id BIGINT PRIMARY KEY, question VARCHAR(255), answer VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS itm_img (id BIGINT PRIMARY KEY, img_url VARCHAR(255), img_type VARCHAR(30), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS itm_display (id BIGINT PRIMARY KEY, display_yn CHAR(1), display_order INT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS itm_vendor (id BIGINT PRIMARY KEY, vendor_cd VARCHAR(40), vendor_name VARCHAR(120), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS itm_discount (id BIGINT PRIMARY KEY, discount_rate DECIMAL(5,2), discount_desc VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

INSERT INTO itm_base (id, item_no, item_name) VALUES (1, 'I0001', 'Seed Item') ON DUPLICATE KEY UPDATE item_name=VALUES(item_name);
INSERT INTO itm_price (id, price_amt, currency) VALUES (1, 12000.00, 'KRW') ON DUPLICATE KEY UPDATE price_amt=VALUES(price_amt);
INSERT INTO itm_stock (id, stock_qty, warehouse_cd) VALUES (1, 100, 'WH01') ON DUPLICATE KEY UPDATE stock_qty=VALUES(stock_qty);
INSERT INTO itm_category (id, category_cd, category_name) VALUES (1, 'C001', 'Seed Category') ON DUPLICATE KEY UPDATE category_name=VALUES(category_name);
INSERT INTO itm_review (id, rating, review_text) VALUES (1, 5, 'seed') ON DUPLICATE KEY UPDATE review_text=VALUES(review_text);
INSERT INTO itm_qna (id, question, answer) VALUES (1, 'seed q', 'seed a') ON DUPLICATE KEY UPDATE answer=VALUES(answer);
INSERT INTO itm_img (id, img_url, img_type) VALUES (1, 'https://example.com/1.jpg', 'MAIN') ON DUPLICATE KEY UPDATE img_url=VALUES(img_url);
INSERT INTO itm_display (id, display_yn, display_order) VALUES (1, 'Y', 1) ON DUPLICATE KEY UPDATE display_yn=VALUES(display_yn);
INSERT INTO itm_vendor (id, vendor_cd, vendor_name) VALUES (1, 'V001', 'Seed Vendor') ON DUPLICATE KEY UPDATE vendor_name=VALUES(vendor_name);
INSERT INTO itm_discount (id, discount_rate, discount_desc) VALUES (1, 10.00, 'seed') ON DUPLICATE KEY UPDATE discount_rate=VALUES(discount_rate);

USE cust_db;
CREATE TABLE IF NOT EXISTS cst_base (id BIGINT PRIMARY KEY, cust_no VARCHAR(30), cust_name VARCHAR(100), cst_phone VARCHAR(40), cst_email VARCHAR(150), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS cst_addr (id BIGINT PRIMARY KEY, zip_no VARCHAR(10), addr1 VARCHAR(150), addr2 VARCHAR(150), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS cst_term (id BIGINT PRIMARY KEY, term_code VARCHAR(30), agree_yn CHAR(1), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS cst_black (id BIGINT PRIMARY KEY, black_yn CHAR(1), reason VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS cst_counsel (id BIGINT PRIMARY KEY, channel VARCHAR(30), contents VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS cst_memo (id BIGINT PRIMARY KEY, memo_text VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS cst_group (id BIGINT PRIMARY KEY, group_cd VARCHAR(30), group_name VARCHAR(100), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS cst_event (id BIGINT PRIMARY KEY, event_cd VARCHAR(40), event_name VARCHAR(120), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS cst_coupon (id BIGINT PRIMARY KEY, coupon_no VARCHAR(40), coupon_desc VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS cst_benefit (id BIGINT PRIMARY KEY, benefit_type VARCHAR(40), benefit_desc VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

INSERT INTO cst_base (id, cust_no, cust_name, cst_phone, cst_email) VALUES
  (1, 'C0001', 'Lee Cust', '01099887766', 'lee.cust@example.com')
ON DUPLICATE KEY UPDATE cust_name=VALUES(cust_name);
INSERT INTO cst_addr (id, zip_no, addr1, addr2) VALUES (1, '06123', 'Seoul', 'Test-ro 1') ON DUPLICATE KEY UPDATE addr1=VALUES(addr1);
INSERT INTO cst_term (id, term_code, agree_yn) VALUES (1, 'T001', 'Y') ON DUPLICATE KEY UPDATE agree_yn=VALUES(agree_yn);
INSERT INTO cst_black (id, black_yn, reason) VALUES (1, 'N', 'seed') ON DUPLICATE KEY UPDATE black_yn=VALUES(black_yn);
INSERT INTO cst_counsel (id, channel, contents) VALUES (1, 'CALL', 'seed') ON DUPLICATE KEY UPDATE contents=VALUES(contents);
INSERT INTO cst_memo (id, memo_text) VALUES (1, 'seed') ON DUPLICATE KEY UPDATE memo_text=VALUES(memo_text);
INSERT INTO cst_group (id, group_cd, group_name) VALUES (1, 'GRP1', 'Seed Group') ON DUPLICATE KEY UPDATE group_name=VALUES(group_name);
INSERT INTO cst_event (id, event_cd, event_name) VALUES (1, 'EVT1', 'Seed Event') ON DUPLICATE KEY UPDATE event_name=VALUES(event_name);
INSERT INTO cst_coupon (id, coupon_no, coupon_desc) VALUES (1, 'CPN1', 'seed') ON DUPLICATE KEY UPDATE coupon_desc=VALUES(coupon_desc);
INSERT INTO cst_benefit (id, benefit_type, benefit_desc) VALUES (1, 'POINT', 'seed') ON DUPLICATE KEY UPDATE benefit_desc=VALUES(benefit_desc);


/* =========================================================
   [SECTION B] Tibero 6/7
   - Run as each schema user (MEMBER_DB / ITEM_DB / CUST_DB),
     or create synonyms from a DBA account as needed.
   ========================================================= */

-- MEMBER_DB
CREATE TABLE MBR_BASE (ID NUMBER PRIMARY KEY, MEMBER_NO VARCHAR2(30), MBR_NAME VARCHAR2(100), RESIDENT_NO VARCHAR2(64), MOBILE_NO VARCHAR2(30), MBR_DETAIL VARCHAR2(255), MBR_AUTH VARCHAR2(255), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE MBR_DETAIL (ID NUMBER PRIMARY KEY, EMAIL VARCHAR2(150), ADDR_DETAIL VARCHAR2(255), NOTE VARCHAR2(255), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE MBR_LOG_01 (ID NUMBER PRIMARY KEY, EVENT_TYPE VARCHAR2(40), MESSAGE VARCHAR2(255), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE MBR_LOG_02 (ID NUMBER PRIMARY KEY, EVENT_TYPE VARCHAR2(40), MESSAGE VARCHAR2(255), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE MBR_LOG_03 (ID NUMBER PRIMARY KEY, EVENT_TYPE VARCHAR2(40), MESSAGE VARCHAR2(255), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE MBR_AUTH (ID NUMBER PRIMARY KEY, AUTH_CODE VARCHAR2(100), AUTH_DESC VARCHAR2(255), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE MBR_SNS (ID NUMBER PRIMARY KEY, SNS_TYPE VARCHAR2(30), SNS_ID VARCHAR2(120), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE MBR_POINT (ID NUMBER PRIMARY KEY, POINT_AMT NUMBER, REASON VARCHAR2(255), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE MBR_GRADE (ID NUMBER PRIMARY KEY, GRADE_CODE VARCHAR2(30), GRADE_NAME VARCHAR2(100), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE MBR_DORMANT (ID NUMBER PRIMARY KEY, DORMANT_YN CHAR(1), DORMANT_AT TIMESTAMP, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

INSERT INTO MBR_BASE (ID, MEMBER_NO, MBR_NAME, RESIDENT_NO, MOBILE_NO, MBR_DETAIL, MBR_AUTH) VALUES (1, 'M0001', 'Kim DA', '900101-1234567', '01012345678', 'damo_payload_001', 'damo_auth_001');
INSERT INTO MBR_DETAIL (ID, EMAIL, ADDR_DETAIL, NOTE) VALUES (1, 'kim.da@example.com', 'Seoul Test-gu 101', 'seed');
INSERT INTO MBR_LOG_01 (ID, EVENT_TYPE, MESSAGE) VALUES (1, 'LOGIN', 'seed');
INSERT INTO MBR_LOG_02 (ID, EVENT_TYPE, MESSAGE) VALUES (1, 'LOGIN', 'seed');
INSERT INTO MBR_LOG_03 (ID, EVENT_TYPE, MESSAGE) VALUES (1, 'LOGIN', 'seed');
INSERT INTO MBR_AUTH (ID, AUTH_CODE, AUTH_DESC) VALUES (1, 'ROLE_USER', 'seed');
INSERT INTO MBR_SNS (ID, SNS_TYPE, SNS_ID) VALUES (1, 'KAKAO', 'kakao_001');
INSERT INTO MBR_POINT (ID, POINT_AMT, REASON) VALUES (1, 1000, 'seed');
INSERT INTO MBR_GRADE (ID, GRADE_CODE, GRADE_NAME) VALUES (1, 'GOLD', 'Gold');
INSERT INTO MBR_DORMANT (ID, DORMANT_YN, DORMANT_AT) VALUES (1, 'N', NULL);

-- ITEM_DB
CREATE TABLE ITM_BASE (ID NUMBER PRIMARY KEY, ITEM_NO VARCHAR2(40), ITEM_NAME VARCHAR2(150), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE ITM_PRICE (ID NUMBER PRIMARY KEY, PRICE_AMT NUMBER(15,2), CURRENCY VARCHAR2(10), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE ITM_STOCK (ID NUMBER PRIMARY KEY, STOCK_QTY NUMBER, WAREHOUSE_CD VARCHAR2(30), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE ITM_CATEGORY (ID NUMBER PRIMARY KEY, CATEGORY_CD VARCHAR2(40), CATEGORY_NAME VARCHAR2(100), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE ITM_REVIEW (ID NUMBER PRIMARY KEY, RATING NUMBER, REVIEW_TEXT VARCHAR2(255), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE ITM_QNA (ID NUMBER PRIMARY KEY, QUESTION VARCHAR2(255), ANSWER VARCHAR2(255), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE ITM_IMG (ID NUMBER PRIMARY KEY, IMG_URL VARCHAR2(255), IMG_TYPE VARCHAR2(30), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE ITM_DISPLAY (ID NUMBER PRIMARY KEY, DISPLAY_YN CHAR(1), DISPLAY_ORDER NUMBER, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE ITM_VENDOR (ID NUMBER PRIMARY KEY, VENDOR_CD VARCHAR2(40), VENDOR_NAME VARCHAR2(120), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE ITM_DISCOUNT (ID NUMBER PRIMARY KEY, DISCOUNT_RATE NUMBER(5,2), DISCOUNT_DESC VARCHAR2(255), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

INSERT INTO ITM_BASE (ID, ITEM_NO, ITEM_NAME) VALUES (1, 'I0001', 'Seed Item');
INSERT INTO ITM_PRICE (ID, PRICE_AMT, CURRENCY) VALUES (1, 12000.00, 'KRW');
INSERT INTO ITM_STOCK (ID, STOCK_QTY, WAREHOUSE_CD) VALUES (1, 100, 'WH01');
INSERT INTO ITM_CATEGORY (ID, CATEGORY_CD, CATEGORY_NAME) VALUES (1, 'C001', 'Seed Category');
INSERT INTO ITM_REVIEW (ID, RATING, REVIEW_TEXT) VALUES (1, 5, 'seed');
INSERT INTO ITM_QNA (ID, QUESTION, ANSWER) VALUES (1, 'seed q', 'seed a');
INSERT INTO ITM_IMG (ID, IMG_URL, IMG_TYPE) VALUES (1, 'https://example.com/1.jpg', 'MAIN');
INSERT INTO ITM_DISPLAY (ID, DISPLAY_YN, DISPLAY_ORDER) VALUES (1, 'Y', 1);
INSERT INTO ITM_VENDOR (ID, VENDOR_CD, VENDOR_NAME) VALUES (1, 'V001', 'Seed Vendor');
INSERT INTO ITM_DISCOUNT (ID, DISCOUNT_RATE, DISCOUNT_DESC) VALUES (1, 10.00, 'seed');

-- CUST_DB
CREATE TABLE CST_BASE (ID NUMBER PRIMARY KEY, CUST_NO VARCHAR2(30), CUST_NAME VARCHAR2(100), CST_PHONE VARCHAR2(40), CST_EMAIL VARCHAR2(150), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE CST_ADDR (ID NUMBER PRIMARY KEY, ZIP_NO VARCHAR2(10), ADDR1 VARCHAR2(150), ADDR2 VARCHAR2(150), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE CST_TERM (ID NUMBER PRIMARY KEY, TERM_CODE VARCHAR2(30), AGREE_YN CHAR(1), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE CST_BLACK (ID NUMBER PRIMARY KEY, BLACK_YN CHAR(1), REASON VARCHAR2(255), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE CST_COUNSEL (ID NUMBER PRIMARY KEY, CHANNEL VARCHAR2(30), CONTENTS VARCHAR2(255), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE CST_MEMO (ID NUMBER PRIMARY KEY, MEMO_TEXT VARCHAR2(255), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE CST_GROUP (ID NUMBER PRIMARY KEY, GROUP_CD VARCHAR2(30), GROUP_NAME VARCHAR2(100), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE CST_EVENT (ID NUMBER PRIMARY KEY, EVENT_CD VARCHAR2(40), EVENT_NAME VARCHAR2(120), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE CST_COUPON (ID NUMBER PRIMARY KEY, COUPON_NO VARCHAR2(40), COUPON_DESC VARCHAR2(255), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE CST_BENEFIT (ID NUMBER PRIMARY KEY, BENEFIT_TYPE VARCHAR2(40), BENEFIT_DESC VARCHAR2(255), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

INSERT INTO CST_BASE (ID, CUST_NO, CUST_NAME, CST_PHONE, CST_EMAIL) VALUES (1, 'C0001', 'Lee Cust', '01099887766', 'lee.cust@example.com');
INSERT INTO CST_ADDR (ID, ZIP_NO, ADDR1, ADDR2) VALUES (1, '06123', 'Seoul', 'Test-ro 1');
INSERT INTO CST_TERM (ID, TERM_CODE, AGREE_YN) VALUES (1, 'T001', 'Y');
INSERT INTO CST_BLACK (ID, BLACK_YN, REASON) VALUES (1, 'N', 'seed');
INSERT INTO CST_COUNSEL (ID, CHANNEL, CONTENTS) VALUES (1, 'CALL', 'seed');
INSERT INTO CST_MEMO (ID, MEMO_TEXT) VALUES (1, 'seed');
INSERT INTO CST_GROUP (ID, GROUP_CD, GROUP_NAME) VALUES (1, 'GRP1', 'Seed Group');
INSERT INTO CST_EVENT (ID, EVENT_CD, EVENT_NAME) VALUES (1, 'EVT1', 'Seed Event');
INSERT INTO CST_COUPON (ID, COUPON_NO, COUPON_DESC) VALUES (1, 'CPN1', 'seed');
INSERT INTO CST_BENEFIT (ID, BENEFIT_TYPE, BENEFIT_DESC) VALUES (1, 'POINT', 'seed');

COMMIT;

/* =========================================================
   [SECTION C] Bulk seed to 100 rows per table
   - Existing ID=1 row is preserved.
   - This section adds ID 2..100.
   ========================================================= */

/* ---------- C-1. MySQL 8.x (ID 2..100) ---------- */

INSERT INTO member_db.mbr_base (id, member_no, mbr_name, resident_no, mobile_no, mbr_detail, mbr_auth)
SELECT n, CONCAT('M', LPAD(n, 4, '0')), CONCAT('Kim DA ', n), CONCAT('900101-', LPAD(n, 7, '0')), CONCAT('010', LPAD(n, 8, '0')), CONCAT('damo_payload_', LPAD(n, 3, '0')), CONCAT('damo_auth_', LPAD(n, 3, '0'))
FROM (SELECT 2 n UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10
      UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15 UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19 UNION ALL SELECT 20
      UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24 UNION ALL SELECT 25 UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL SELECT 28 UNION ALL SELECT 29 UNION ALL SELECT 30
      UNION ALL SELECT 31 UNION ALL SELECT 32 UNION ALL SELECT 33 UNION ALL SELECT 34 UNION ALL SELECT 35 UNION ALL SELECT 36 UNION ALL SELECT 37 UNION ALL SELECT 38 UNION ALL SELECT 39 UNION ALL SELECT 40
      UNION ALL SELECT 41 UNION ALL SELECT 42 UNION ALL SELECT 43 UNION ALL SELECT 44 UNION ALL SELECT 45 UNION ALL SELECT 46 UNION ALL SELECT 47 UNION ALL SELECT 48 UNION ALL SELECT 49 UNION ALL SELECT 50
      UNION ALL SELECT 51 UNION ALL SELECT 52 UNION ALL SELECT 53 UNION ALL SELECT 54 UNION ALL SELECT 55 UNION ALL SELECT 56 UNION ALL SELECT 57 UNION ALL SELECT 58 UNION ALL SELECT 59 UNION ALL SELECT 60
      UNION ALL SELECT 61 UNION ALL SELECT 62 UNION ALL SELECT 63 UNION ALL SELECT 64 UNION ALL SELECT 65 UNION ALL SELECT 66 UNION ALL SELECT 67 UNION ALL SELECT 68 UNION ALL SELECT 69 UNION ALL SELECT 70
      UNION ALL SELECT 71 UNION ALL SELECT 72 UNION ALL SELECT 73 UNION ALL SELECT 74 UNION ALL SELECT 75 UNION ALL SELECT 76 UNION ALL SELECT 77 UNION ALL SELECT 78 UNION ALL SELECT 79 UNION ALL SELECT 80
      UNION ALL SELECT 81 UNION ALL SELECT 82 UNION ALL SELECT 83 UNION ALL SELECT 84 UNION ALL SELECT 85 UNION ALL SELECT 86 UNION ALL SELECT 87 UNION ALL SELECT 88 UNION ALL SELECT 89 UNION ALL SELECT 90
      UNION ALL SELECT 91 UNION ALL SELECT 92 UNION ALL SELECT 93 UNION ALL SELECT 94 UNION ALL SELECT 95 UNION ALL SELECT 96 UNION ALL SELECT 97 UNION ALL SELECT 98 UNION ALL SELECT 99 UNION ALL SELECT 100) nums;

INSERT INTO member_db.mbr_detail (id, email, addr_detail, note) SELECT id, CONCAT('member', id, '@example.com'), CONCAT('Seoul Test-gu ', id), CONCAT('seed_', id) FROM member_db.mbr_base WHERE id BETWEEN 2 AND 100;
INSERT INTO member_db.mbr_log_01 (id, event_type, message) SELECT id, 'LOGIN', CONCAT('seed_', id) FROM member_db.mbr_base WHERE id BETWEEN 2 AND 100;
INSERT INTO member_db.mbr_log_02 (id, event_type, message) SELECT id, 'LOGIN', CONCAT('seed_', id) FROM member_db.mbr_base WHERE id BETWEEN 2 AND 100;
INSERT INTO member_db.mbr_log_03 (id, event_type, message) SELECT id, 'LOGIN', CONCAT('seed_', id) FROM member_db.mbr_base WHERE id BETWEEN 2 AND 100;
INSERT INTO member_db.mbr_auth (id, auth_code, auth_desc) SELECT id, CONCAT('ROLE_', id), CONCAT('seed_', id) FROM member_db.mbr_base WHERE id BETWEEN 2 AND 100;
INSERT INTO member_db.mbr_sns (id, sns_type, sns_id) SELECT id, 'KAKAO', CONCAT('kakao_', LPAD(id, 3, '0')) FROM member_db.mbr_base WHERE id BETWEEN 2 AND 100;
INSERT INTO member_db.mbr_point (id, point_amt, reason) SELECT id, id * 10, CONCAT('seed_', id) FROM member_db.mbr_base WHERE id BETWEEN 2 AND 100;
INSERT INTO member_db.mbr_grade (id, grade_code, grade_name) SELECT id, CONCAT('G', LPAD(id, 3, '0')), CONCAT('Grade ', id) FROM member_db.mbr_base WHERE id BETWEEN 2 AND 100;
INSERT INTO member_db.mbr_dormant (id, dormant_yn, dormant_at) SELECT id, 'N', NULL FROM member_db.mbr_base WHERE id BETWEEN 2 AND 100;

INSERT INTO item_db.itm_base (id, item_no, item_name) SELECT id, CONCAT('I', LPAD(id, 4, '0')), CONCAT('Seed Item ', id) FROM member_db.mbr_base WHERE id BETWEEN 2 AND 100;
INSERT INTO item_db.itm_price (id, price_amt, currency) SELECT id, 1000 + (id * 100), 'KRW' FROM member_db.mbr_base WHERE id BETWEEN 2 AND 100;
INSERT INTO item_db.itm_stock (id, stock_qty, warehouse_cd) SELECT id, 100 + id, CONCAT('WH', LPAD((id % 10) + 1, 2, '0')) FROM member_db.mbr_base WHERE id BETWEEN 2 AND 100;
INSERT INTO item_db.itm_category (id, category_cd, category_name) SELECT id, CONCAT('C', LPAD((id % 20) + 1, 3, '0')), CONCAT('Category ', id) FROM member_db.mbr_base WHERE id BETWEEN 2 AND 100;
INSERT INTO item_db.itm_review (id, rating, review_text) SELECT id, ((id - 1) % 5) + 1, CONCAT('seed_review_', id) FROM member_db.mbr_base WHERE id BETWEEN 2 AND 100;
INSERT INTO item_db.itm_qna (id, question, answer) SELECT id, CONCAT('seed question ', id), CONCAT('seed answer ', id) FROM member_db.mbr_base WHERE id BETWEEN 2 AND 100;
INSERT INTO item_db.itm_img (id, img_url, img_type) SELECT id, CONCAT('https://example.com/', id, '.jpg'), 'MAIN' FROM member_db.mbr_base WHERE id BETWEEN 2 AND 100;
INSERT INTO item_db.itm_display (id, display_yn, display_order) SELECT id, 'Y', id FROM member_db.mbr_base WHERE id BETWEEN 2 AND 100;
INSERT INTO item_db.itm_vendor (id, vendor_cd, vendor_name) SELECT id, CONCAT('V', LPAD((id % 15) + 1, 3, '0')), CONCAT('Vendor ', id) FROM member_db.mbr_base WHERE id BETWEEN 2 AND 100;
INSERT INTO item_db.itm_discount (id, discount_rate, discount_desc) SELECT id, (id % 30), CONCAT('seed_discount_', id) FROM member_db.mbr_base WHERE id BETWEEN 2 AND 100;

INSERT INTO cust_db.cst_base (id, cust_no, cust_name, cst_phone, cst_email) SELECT id, CONCAT('C', LPAD(id, 4, '0')), CONCAT('Lee Cust ', id), CONCAT('010', LPAD(70000000 + id, 8, '0')), CONCAT('cust', id, '@example.com') FROM member_db.mbr_base WHERE id BETWEEN 2 AND 100;
INSERT INTO cust_db.cst_addr (id, zip_no, addr1, addr2) SELECT id, LPAD(60000 + id, 5, '0'), 'Seoul', CONCAT('Test-ro ', id) FROM member_db.mbr_base WHERE id BETWEEN 2 AND 100;
INSERT INTO cust_db.cst_term (id, term_code, agree_yn) SELECT id, CONCAT('T', LPAD((id % 20) + 1, 3, '0')), 'Y' FROM member_db.mbr_base WHERE id BETWEEN 2 AND 100;
INSERT INTO cust_db.cst_black (id, black_yn, reason) SELECT id, 'N', CONCAT('seed_', id) FROM member_db.mbr_base WHERE id BETWEEN 2 AND 100;
INSERT INTO cust_db.cst_counsel (id, channel, contents) SELECT id, 'CALL', CONCAT('seed_', id) FROM member_db.mbr_base WHERE id BETWEEN 2 AND 100;
INSERT INTO cust_db.cst_memo (id, memo_text) SELECT id, CONCAT('seed_', id) FROM member_db.mbr_base WHERE id BETWEEN 2 AND 100;
INSERT INTO cust_db.cst_group (id, group_cd, group_name) SELECT id, CONCAT('GRP', (id % 10) + 1), CONCAT('Group ', id) FROM member_db.mbr_base WHERE id BETWEEN 2 AND 100;
INSERT INTO cust_db.cst_event (id, event_cd, event_name) SELECT id, CONCAT('EVT', (id % 20) + 1), CONCAT('Event ', id) FROM member_db.mbr_base WHERE id BETWEEN 2 AND 100;
INSERT INTO cust_db.cst_coupon (id, coupon_no, coupon_desc) SELECT id, CONCAT('CPN', LPAD(id, 4, '0')), CONCAT('seed_', id) FROM member_db.mbr_base WHERE id BETWEEN 2 AND 100;
INSERT INTO cust_db.cst_benefit (id, benefit_type, benefit_desc) SELECT id, 'POINT', CONCAT('seed_', id) FROM member_db.mbr_base WHERE id BETWEEN 2 AND 100;

/* ---------- C-2. Tibero (ID 2..100) ---------- */

INSERT INTO MBR_BASE (ID, MEMBER_NO, MBR_NAME, RESIDENT_NO, MOBILE_NO, MBR_DETAIL, MBR_AUTH)
SELECT LEVEL, 'M' || LPAD(LEVEL, 4, '0'), 'Kim DA ' || LEVEL, '900101-' || LPAD(LEVEL, 7, '0'), '010' || LPAD(LEVEL, 8, '0'), 'damo_payload_' || LPAD(LEVEL, 3, '0'), 'damo_auth_' || LPAD(LEVEL, 3, '0')
FROM dual CONNECT BY LEVEL <= 99;
INSERT INTO MBR_DETAIL (ID, EMAIL, ADDR_DETAIL, NOTE) SELECT LEVEL, 'member' || LEVEL || '@example.com', 'Seoul Test-gu ' || LEVEL, 'seed_' || LEVEL FROM dual CONNECT BY LEVEL <= 99;
INSERT INTO MBR_LOG_01 (ID, EVENT_TYPE, MESSAGE) SELECT LEVEL, 'LOGIN', 'seed_' || LEVEL FROM dual CONNECT BY LEVEL <= 99;
INSERT INTO MBR_LOG_02 (ID, EVENT_TYPE, MESSAGE) SELECT LEVEL, 'LOGIN', 'seed_' || LEVEL FROM dual CONNECT BY LEVEL <= 99;
INSERT INTO MBR_LOG_03 (ID, EVENT_TYPE, MESSAGE) SELECT LEVEL, 'LOGIN', 'seed_' || LEVEL FROM dual CONNECT BY LEVEL <= 99;
INSERT INTO MBR_AUTH (ID, AUTH_CODE, AUTH_DESC) SELECT LEVEL, 'ROLE_' || LEVEL, 'seed_' || LEVEL FROM dual CONNECT BY LEVEL <= 99;
INSERT INTO MBR_SNS (ID, SNS_TYPE, SNS_ID) SELECT LEVEL, 'KAKAO', 'kakao_' || LPAD(LEVEL, 3, '0') FROM dual CONNECT BY LEVEL <= 99;
INSERT INTO MBR_POINT (ID, POINT_AMT, REASON) SELECT LEVEL, LEVEL * 10, 'seed_' || LEVEL FROM dual CONNECT BY LEVEL <= 99;
INSERT INTO MBR_GRADE (ID, GRADE_CODE, GRADE_NAME) SELECT LEVEL, 'G' || LPAD(LEVEL, 3, '0'), 'Grade ' || LEVEL FROM dual CONNECT BY LEVEL <= 99;
INSERT INTO MBR_DORMANT (ID, DORMANT_YN, DORMANT_AT) SELECT LEVEL, 'N', NULL FROM dual CONNECT BY LEVEL <= 99;

INSERT INTO ITM_BASE (ID, ITEM_NO, ITEM_NAME) SELECT LEVEL, 'I' || LPAD(LEVEL, 4, '0'), 'Seed Item ' || LEVEL FROM dual CONNECT BY LEVEL <= 99;
INSERT INTO ITM_PRICE (ID, PRICE_AMT, CURRENCY) SELECT LEVEL, 1000 + (LEVEL * 100), 'KRW' FROM dual CONNECT BY LEVEL <= 99;
INSERT INTO ITM_STOCK (ID, STOCK_QTY, WAREHOUSE_CD) SELECT LEVEL, 100 + LEVEL, 'WH' || LPAD(MOD(LEVEL, 10) + 1, 2, '0') FROM dual CONNECT BY LEVEL <= 99;
INSERT INTO ITM_CATEGORY (ID, CATEGORY_CD, CATEGORY_NAME) SELECT LEVEL, 'C' || LPAD(MOD(LEVEL, 20) + 1, 3, '0'), 'Category ' || LEVEL FROM dual CONNECT BY LEVEL <= 99;
INSERT INTO ITM_REVIEW (ID, RATING, REVIEW_TEXT) SELECT LEVEL, MOD(LEVEL - 1, 5) + 1, 'seed_review_' || LEVEL FROM dual CONNECT BY LEVEL <= 99;
INSERT INTO ITM_QNA (ID, QUESTION, ANSWER) SELECT LEVEL, 'seed question ' || LEVEL, 'seed answer ' || LEVEL FROM dual CONNECT BY LEVEL <= 99;
INSERT INTO ITM_IMG (ID, IMG_URL, IMG_TYPE) SELECT LEVEL, 'https://example.com/' || LEVEL || '.jpg', 'MAIN' FROM dual CONNECT BY LEVEL <= 99;
INSERT INTO ITM_DISPLAY (ID, DISPLAY_YN, DISPLAY_ORDER) SELECT LEVEL, 'Y', LEVEL FROM dual CONNECT BY LEVEL <= 99;
INSERT INTO ITM_VENDOR (ID, VENDOR_CD, VENDOR_NAME) SELECT LEVEL, 'V' || LPAD(MOD(LEVEL, 15) + 1, 3, '0'), 'Vendor ' || LEVEL FROM dual CONNECT BY LEVEL <= 99;
INSERT INTO ITM_DISCOUNT (ID, DISCOUNT_RATE, DISCOUNT_DESC) SELECT LEVEL, MOD(LEVEL, 30), 'seed_discount_' || LEVEL FROM dual CONNECT BY LEVEL <= 99;

INSERT INTO CST_BASE (ID, CUST_NO, CUST_NAME, CST_PHONE, CST_EMAIL) SELECT LEVEL, 'C' || LPAD(LEVEL, 4, '0'), 'Lee Cust ' || LEVEL, '010' || LPAD(70000000 + LEVEL, 8, '0'), 'cust' || LEVEL || '@example.com' FROM dual CONNECT BY LEVEL <= 99;
INSERT INTO CST_ADDR (ID, ZIP_NO, ADDR1, ADDR2) SELECT LEVEL, LPAD(60000 + LEVEL, 5, '0'), 'Seoul', 'Test-ro ' || LEVEL FROM dual CONNECT BY LEVEL <= 99;
INSERT INTO CST_TERM (ID, TERM_CODE, AGREE_YN) SELECT LEVEL, 'T' || LPAD(MOD(LEVEL, 20) + 1, 3, '0'), 'Y' FROM dual CONNECT BY LEVEL <= 99;
INSERT INTO CST_BLACK (ID, BLACK_YN, REASON) SELECT LEVEL, 'N', 'seed_' || LEVEL FROM dual CONNECT BY LEVEL <= 99;
INSERT INTO CST_COUNSEL (ID, CHANNEL, CONTENTS) SELECT LEVEL, 'CALL', 'seed_' || LEVEL FROM dual CONNECT BY LEVEL <= 99;
INSERT INTO CST_MEMO (ID, MEMO_TEXT) SELECT LEVEL, 'seed_' || LEVEL FROM dual CONNECT BY LEVEL <= 99;
INSERT INTO CST_GROUP (ID, GROUP_CD, GROUP_NAME) SELECT LEVEL, 'GRP' || (MOD(LEVEL, 10) + 1), 'Group ' || LEVEL FROM dual CONNECT BY LEVEL <= 99;
INSERT INTO CST_EVENT (ID, EVENT_CD, EVENT_NAME) SELECT LEVEL, 'EVT' || (MOD(LEVEL, 20) + 1), 'Event ' || LEVEL FROM dual CONNECT BY LEVEL <= 99;
INSERT INTO CST_COUPON (ID, COUPON_NO, COUPON_DESC) SELECT LEVEL, 'CPN' || LPAD(LEVEL, 4, '0'), 'seed_' || LEVEL FROM dual CONNECT BY LEVEL <= 99;
INSERT INTO CST_BENEFIT (ID, BENEFIT_TYPE, BENEFIT_DESC) SELECT LEVEL, 'POINT', 'seed_' || LEVEL FROM dual CONNECT BY LEVEL <= 99;

COMMIT;
